AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/LambdaCall:
  Enabled: false